Presentation/Pages/Admin/Artwork/ArtworkList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;

namespace Presentation.Pages.Admin.Artwork;

[Authorize(Policy = "RequireAdminRole")]
public class ArtworkList : PageModel
{
    private readonly IArtworkRepository _artworkRepository;
    public ArtworkList(IArtworkRepository artworkRepository)
    {
        _artworkRepository = artworkRepository;
    }
    
    [BindProperty]
    public IList<BusinessObject.Entities.Artwork> Artworks { get; set; }
    public async Task OnGet()
    {
        Artworks = await _artworkRepository.GetArtworkAdmin();
    }

    public async Task<IActionResult> OnPostChangeStatus(int Id)
    {
        await _artworkRepository.ChangeArtworkStatusAdmin(Id);
        await OnGet();
        return Page();
    }
}

Presentation/Pages/User/ArtworkList.cshtml.cs
using BusinessObject.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Extensions;
using Repository;

namespace Presentation.Pages.User;

[Authorize]
public class ArtworkList : PageModel
{
    private readonly IPurchaseRepository _purchaseRepository;

    public ArtworkList(IPurchaseRepository purchaseRepository)
    {
        _purchaseRepository = purchaseRepository;
    }
    
    
    [BindProperty]
    public List<Purchase> Purchases { get; set; }
    
    public async Task OnGet()
    {
        Purchases = await _purchaseRepository.GetBuyListForUsers(User.GetUserId());
    }
}

Presentation/Pages/Admin/Artwork/ArtworkList.cshtml
@page
@model Presentation.Pages.Admin.Artwork.ArtworkList

@{
    ViewData["Title"] = "Artwork Management";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css" rel="stylesheet" />  <h1>Artwork Management</h1>
<hr/>
<style>
    body {
        font-size: 16px; /* Adjust as needed */
    }
    .container {
        padding: 20px; /* Adjust padding as needed */
    }
    #purchaseTable th, #purchaseTable td {
        padding: 10px; /* Adjust cell padding as needed */
    }
</style>
<div class="container">
    <div class="row mb-3">
        <div class="col-md-6">
            <h3>Artwork List</h3>
        </div>
    </div>

    @if (Model.Artworks == null || Model.Artworks.Count == 0)
    {
        <div class="alert alert-danger" role="alert">
            No artwork to display!
        </div>
    }
    else
    {
        <table id="artworkTable" class="table table-hover table-bordered dataTable" style="width:100%">  <thead>
                <tr>
                    <th scope="col">Artwork Id</th>
                    <th scope="col">Artwork Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Genre</th>
                    <th scope="col">Price</th>
                    <th scope="col">Create Date</th>
                    <th scope="col">Status</th>
                    <th scope="col">Like Number</th>
                    <th scope="col">Comment Number</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Artworks)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Title</td>
                        <td>@item.AppUser.UserName</td>
                        <td>@item.Genre.Name</td>
                        <td>@item.Price.ToString("C", System.Globalization.CultureInfo.GetCultureInfoByIetfLanguageTag("en-US"))</td>
                        <td>@item.CreatedDate</td>
                        <td>
                            @if (item.Status == 1)
                            {
                                <span class="badge bg-success">Active</span>
                            }
                            else
                            {
                                <span class="badge bg-danger">Inactive</span>
                            }
                        </td>
                        <td>@item.Likes.Count</td>
                        <td>@item.Comments.Count</td>
                        <td>
                            <form asp-page-handler="ChangeStatus" asp-route-id="@item.Id" method="post">
                                <button type="submit" class="btn btn-sm btn-primary">
                                    <i class="fas fa-exchange-alt"></i> Change Status
                                </button>
                                <input type="hidden" name="id" value="@item.Id"/>
                            </form>
                            <a asp-page="/Home/ArtworkDetail" asp-route-id="@item.Id">
                                <button class="btn btn-sm btn-secondary">
                                    <i class="fas fa-eye"></i> Details
                                </button>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

@section Scripts {
    <script>
         let table = new DataTable('#artworkTable', {
                    responsive: true
                });
    </script>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.13.1"></script>
    }