Presentation/Pages/Artist/AddCommission.cshtml.cs
using AutoMapper;
using BusinessObject.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Extensions;
using Repository;

namespace Presentation.Pages.Artist
{
    
    [Authorize(Policy = "RequireArtistRole")]
    public class AddCommissionModel : PageModel
    {
		private readonly ICommissionRepository _commissionRepository;
		private readonly IMapper _mapper;

		public AddCommissionModel(
            ICommissionRepository commissionRepository,
            IMapper mapper
            )
        {
			_commissionRepository = commissionRepository;
			_mapper = mapper;
		}
        [BindProperty] 
        public AddCommisionDTO AddCommisionDTO { get; set; } = new AddCommisionDTO();
        public bool IsRegisteredCommission { get; set; }
        public async void OnGetAsync()
        {
            try
            {
                IsRegisteredCommission = await _commissionRepository.CheckArtistRegisterCommission(User.GetUserId());
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            AddCommisionDTO.AppUserId = User.GetUserId();
            if (!ModelState.IsValid) return Page();

            try
            {
                var commission = _mapper.Map<BusinessObject.Entities.Commission>(AddCommisionDTO);
                await _commissionRepository.AddCommission(commission);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
            return RedirectToPage("/artist/artistcommission");
        }
    }
}

Presentation/Pages/Artist/ArtistAddArtwork.cshtml.cs
using AutoMapper;
using BusinessObject.DTOs;
using BusinessObject.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Extensions;
using Repository;

namespace Presentation.Pages.Artist
{
    [Authorize(Policy = "RequireArtistRole")]
    public class ArtistAddArtworkModel : PageModel
	{
		private readonly IArtworkRepository _artworkRepository;
		private readonly IGenreRepository _genreRepository;
		private readonly IUserRepository _userRepository;
		private readonly IMapper _mapper;

		public ArtistAddArtworkModel(
			IArtworkRepository artworkRepository,
			IMapper mapper,
			IUserRepository userRepository,
			IGenreRepository genreRepository
			)
		{
			_artworkRepository = artworkRepository;
			_mapper = mapper;
			_userRepository = userRepository;
			_genreRepository = genreRepository;
		}

		public IEnumerable<Artwork> Artworks { get; set; } = default;
		public IList<ArtworkImage> artworkImage { get; set; }

		[BindProperty]
		public AddArtworkDTO addArtworkDTO { get; set; } = new AddArtworkDTO();
		[BindProperty]
		public AddArtworkImageDTO addArtworkImageDTO { get; set; } = new AddArtworkImageDTO();

		public IEnumerable<Genre> Genres { get; set; }
		public async Task OnGetAsync(int artistid)
		{
			if (artistid != null)
			{
				if (_userRepository != null)
				{
					var artist = await _userRepository.GetUserById(artistid);
				}

				Genres = await _genreRepository.GetAll();
			}

		}

		public async Task<IActionResult> OnPostAddImage()
		{
			Genres = await _genreRepository.GetAll();
			addArtworkDTO.AppUserId = User.GetUserId();
			if (!ModelState.IsValid)
			{
				return Page();
			}
			try
			{
				addArtworkDTO.CreatedDate = DateTime.UtcNow;
				var artwork = _mapper.Map<Artwork>(addArtworkDTO);
				addArtworkImageDTO.isMain = true;
				artwork.ArtworkImage = _mapper.Map<ArtworkImage>(addArtworkImageDTO);
				await _artworkRepository.AddArtwork(artwork);
				TempData["Message"] = "Artwork has been added successfully!";
				return Redirect("/Audience/ArtistPage?userId=" + User.GetUserId());
			}
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
			}

			return Page();
		}
	}
}

Presentation/Pages/Artist/ArtistCommissionHistory.cshtml.cs
using BusinessObject.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Extensions;
using Repository;

namespace Presentation.Pages.Artist
{
	[Authorize(Policy = "RequireArtistRole")]
    public class ArtistCommissionHistoryModel : PageModel
    {
		private readonly ICommissionRepository _commissionRepository;

		public ArtistCommissionHistoryModel(ICommissionRepository commissionRepository)
        {
			_commissionRepository = commissionRepository;
		}
        public List<CommissionRequestHistoryDTO> CommissionRequestHistoryDTOs{ get; set; }
        [BindProperty]
        public int CommissionId { get; set; }
		[BindProperty]
		public decimal MinPrice { get; set; }
		[BindProperty]
		public decimal MaxPrice { get; set; }
		[BindProperty]
		public string? NotAcceptedReason { get; set; }
		[BindProperty]
		public int? ActualPrice { get; set; }
		public bool IsAcceptSuccess { get; set; } = false;
		public bool IsNotAcceptSuccess { get; set; } = false;
		public bool IsDoneSuccess { get; set; } = false;
		public bool IsInvalidAccept { get; set; } = false;
		public bool IsInvalidReject { get; set; } = false;
        public async Task OnGet(int commissionId = 0, string statusFilter = "", string message = "", bool isAcceptSuccess = false, bool isNotAcceptSuccess = false, bool isDoneSuccess = false)
        {
            CommissionRequestHistoryDTOs = await _commissionRepository.GetCommissionRequestHistoryForArtist(User.GetUserId(), statusFilter);
			TempData["Message"] = message;
			IsNotAcceptSuccess = isNotAcceptSuccess;
			IsAcceptSuccess = isAcceptSuccess;
			IsDoneSuccess = isDoneSuccess;
			if(commissionId != 0)
			{
				CommissionId = commissionId;
			}
		}

        public async Task<IActionResult> OnPostAccept()
        {
			CommissionRequestHistoryDTOs = await _commissionRepository.GetCommissionRequestHistoryForArtist(User.GetUserId(), "");
			if(CommissionId == 0)
			{
				ModelState.AddModelError(string.Empty, "Invalid commission");
				IsInvalidAccept = true;
				return Page();
			}
			if (ActualPrice == null || ActualPrice <=0)
			{
				ModelState.AddModelError(string.Empty, "Invalid actual price");
				IsInvalidAccept = true;
				return Page();
			}
			if (ActualPrice < MinPrice || ActualPrice > MaxPrice)
			{
				ModelState.AddModelError(string.Empty, $"Your Price must be between {MinPrice} and {MaxPrice}");
				IsInvalidAccept = true;
				return Page();
			}


			try
            {
                await _commissionRepository.AcceptCommissionRequest(CommissionId, ActualPrice.Value);
				IsInvalidAccept = false;
			}
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
				IsInvalidAccept = true;
				return Page();
            }
			CommissionRequestHistoryDTOs = await _commissionRepository.GetCommissionRequestHistoryForArtist(User.GetUserId(), "");
			return RedirectToPage("/artist/artistcommissionhistory", new
			{
				message = "Commission Accepted",
				isAcceptSuccess = true,
				commissionId = CommissionId
			});
        }

		public async Task<IActionResult> OnPostNotAccept()
		{
			CommissionRequestHistoryDTOs = await _commissionRepository.GetCommissionRequestHistoryForArtist(User.GetUserId(), "");
			if (CommissionId == 0)
			{
				ModelState.AddModelError(string.Empty, "Invalid commission");
				IsInvalidReject = true;
				return Page();
			}
			if (string.IsNullOrEmpty(NotAcceptedReason))
			{
				ModelState.ToList().Clear();
				ModelState.AddModelError(string.Empty, "You must fill out the reject reason");
				IsInvalidReject = true;
				return Page();
			}
			try
			{
				await _commissionRepository.NotAcceptCommissionRequest(CommissionId, NotAcceptedReason);
				IsInvalidReject = false;
			}
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
				IsInvalidReject = true;
				return Page();
			}
			return RedirectToPage("/artist/artistcommissionhistory", new
			{
				message = "Commission Denied",
				isNotAcceptSuccess = true,
				commissionId = CommissionId
			});
		}
	}
}

Presentation/Pages/Artist/ArtistCommissionRequestDetail.cshtml.cs
using AutoMapper;
using BusinessObject.DTOs;
using BusinessObject.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Extensions;
using Presentation.Services;
using Repository;

namespace Presentation.Pages.Artist
{
	[Authorize(Policy = "RequireArtistRole")]
    public class ArtistCommissionRequestDetailModel : PageModel
    {
		private readonly ICommissionRepository _commissionRepository;
		private readonly IImageService _imageService;
		private readonly IMapper _mapper;

		public ArtistCommissionRequestDetailModel(
            ICommissionRepository commissionRepository,
			IImageService imageService,
            IMapper mapper
            )
        {
			_commissionRepository = commissionRepository;
			_imageService = imageService;
			_mapper = mapper;
		}
		public bool IsInvalidAccess { get; set; } = false;
		public bool IsInvalidInput { get; set; } = false;
        public List<CommissionImage> CommissionImages{ get; set; }
        [BindProperty]
        public AddCommissionImageDTO AddCommissionImageDTO{ get; set; } = new AddCommissionImageDTO();
		public DateTime CommissionStartDate { get; set; }
        public DateTime CommissionEndDate { get; set; }
        public bool IsAddImageSuccess { get; set; } = false;
        public async Task OnGet(int id, bool isAddImageSuccess = false)
        {
            var commission = await _commissionRepository.GetSingleCommissionRequestHistory(id);
			
			if(commission != null && commission.ReceiverEmail == User.GetEmailAddress())
			{
				IsInvalidAccess = false;
				CommissionStartDate = commission.RequestDate;
				CommissionEndDate = commission.DueDate;
				CommissionImages = commission.CommissionImages.OrderBy(x => x.CreatedDate).ToList();
				if(CommissionImages.Any())
				{
					CommissionImages.Any(x => x.isMain == true);
					CommissionImages.Last().isMain = true;
				}
				AddCommissionImageDTO.CommissionRequestId = id;
				IsAddImageSuccess = isAddImageSuccess;
			}
			else
			{
				IsInvalidAccess = true;
			}
        }

        public async Task<IActionResult> OnPostAddImage()
        {
            if (!ModelState.IsValid)
            {
				IsInvalidAccess = false;
				IsInvalidInput = true;
				var commission1 = await _commissionRepository.GetSingleCommissionRequestHistory(AddCommissionImageDTO.CommissionRequestId);
                if(commission1 != null)
                {
					CommissionImages = commission1.CommissionImages;
					CommissionStartDate = commission1.RequestDate;
					CommissionEndDate = commission1.RequestDate.AddDays(30);
				}
				return Page();
            }
            try
            {
				AddCommissionImageDTO.DownloadUrl = _imageService.GetImageUploadUrl(AddCommissionImageDTO.PublicId);
				var commissionImage = _mapper.Map<CommissionImage>(AddCommissionImageDTO);
                if (commissionImage != null)
                {
                    commissionImage.isMain = true;
                    commissionImage.CreatedDate = DateTime.UtcNow;
                    await _commissionRepository.AddCommissionImage(commissionImage);
                }
            }
            catch (Exception ex)
            {
				var commission = await _commissionRepository.GetSingleCommissionRequestHistory(AddCommissionImageDTO.CommissionRequestId);
				CommissionImages = commission.CommissionImages;
				ModelState.AddModelError(string.Empty, ex.Message);
				IsInvalidInput = true;
				return Page();
            }
			
			return RedirectToPage("/artist/artistcommissionrequestdetail", new {
				id = AddCommissionImageDTO.CommissionRequestId,
				isAddImageSuccess = true
			});
        }
		public async Task<IActionResult> OnPostDone()
		{
			if (AddCommissionImageDTO.CommissionRequestId == 0)
			{
				var commission1 = await _commissionRepository.GetSingleCommissionRequestHistory(AddCommissionImageDTO.CommissionRequestId);
				if (commission1 != null)
				{
					CommissionImages = commission1.CommissionImages;
				}
				ModelState.AddModelError(string.Empty, "Invalid commission");
				return Page();
			}
			try
			{
				await _commissionRepository.DoneCommissionRequest(AddCommissionImageDTO.CommissionRequestId);
			}
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
				var commission = await _commissionRepository.GetSingleCommissionRequestHistory(AddCommissionImageDTO.CommissionRequestId);
				CommissionImages = commission.CommissionImages;
				return Page();
			}
			return RedirectToPage("/artist/artistcommissionhistory", 
				new 
				{
					message = "You have succesfully confirmed that the commission is done", 
					isDoneSuccess = true,
					commissionId = AddCommissionImageDTO.CommissionRequestId
				}
				);
		}
	}
}

Presentation/Pages/Artist/ArtworkModify.cshtml.cs
using AutoMapper;
using BusinessObject.DTOs;
using BusinessObject.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Extensions;
using Presentation.Services;
using Repository;

namespace Presentation.Pages.Artist
{
    [Authorize(Policy = "RequireArtistRole")]
    public class ArtworkModifyModel : PageModel
    {
		private readonly IArtworkRepository _artworkRepository;
		private readonly IGenreRepository _genreRepository;
		private readonly IUserRepository _userRepository;
        private readonly IImageService _imageService;
        private readonly IMapper _mapper;


		public ArtworkModifyModel(
			IArtworkRepository artworkRepository,
			IMapper mapper,
			IUserRepository userRepository,
			IImageService imageService,
			IGenreRepository genreRepository
			)
		{
			_artworkRepository = artworkRepository;
			_mapper = mapper;
			_userRepository = userRepository;
            _imageService = imageService;
            _genreRepository = genreRepository;
		}

		public Artwork Artwork { get; set; } = default;
		public IList<ArtworkImage> artworkImage { get; set; }

		[BindProperty]
		public AddArtworkDTO addArtworkDTO { get; set; } = new AddArtworkDTO();
		[BindProperty]
		public AddArtworkImageDTO addArtworkImageDTO { get; set; } = new AddArtworkImageDTO();

		public IEnumerable<Genre> Genres { get; set; }
		public int currentUserId = 0;
        public async Task OnGetAsync(int artworkid)
		{
			Artwork = await _artworkRepository.GetArtworkById(artworkid);
			currentUserId = User.GetUserId();
            addArtworkDTO.Id = artworkid;
            if (Artwork != null)
			{
                if (_userRepository != null)
				{
					var artist = await _userRepository.GetUserById(User.GetUserId());
				}

				Genres = await _genreRepository.GetAll();
			}

		}

		public async Task<IActionResult> OnPostDeleteArtwork()
		{
			Genres = await _genreRepository.GetAll();
			addArtworkDTO.AppUserId = User.GetUserId();
            int artworkid = int.Parse(Request.Form["artworkId"]);
            string publicId = Request.Form["publicId"];

            try
			{
				var artwork = _mapper.Map<Artwork>(addArtworkDTO);
                await _artworkRepository.DeleteArtwork(artworkid);
                await _imageService.DeletePhotoAsync(publicId);
                TempData["Message"] = "Artwork has been Deleted successfully!";
                return Redirect("/Audience/ArtistPage?userId=" + User.GetUserId());

            }
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
			}
            currentUserId = User.GetUserId();
            return Page();
		}
	}
}

Presentation/Pages/Artist/EditCommissionImage.cshtml.cs
using BusinessObject.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Extensions;
using Repository;

namespace Presentation.Pages.Artist
{
    public class EditCommissionImageModel : PageModel
    {
		private readonly ICommissionRepository _commissionRepository;

		public EditCommissionImageModel(ICommissionRepository commissionRepository)
        {
			_commissionRepository = commissionRepository;
		}
        [BindProperty]
        public CommissionImage CommissionImage { get; set; }
        public async Task OnGet(int id)
        {
            CommissionImage = await _commissionRepository.GetCommissionImage(id, User.GetUserId());
        }
        public async Task<IActionResult> OnPostEdit()
        {
            if (!ModelState.IsValid) return Page();
            if(string.IsNullOrEmpty(CommissionImage.Description))
            {
                ModelState.AddModelError(string.Empty, "Please enter description");
            }
            try
            {
                await _commissionRepository.EditCommissionImage(CommissionImage);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }
            return RedirectToPage("/artist/artistcommissionrequestdetail", new
            {
                id = CommissionImage.CommissionRequestId
            });
        }
		public async Task<IActionResult> OnPostDelete()
		{
			if (!ModelState.IsValid) return Page();
			try
			{
				await _commissionRepository.Delete(CommissionImage);
			}
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
				return Page();
			}
			return RedirectToPage("/artist/artistcommissionrequestdetail", new
			{
				id = CommissionImage.CommissionRequestId
			});
		}
	}
}

Presentation/Pages/Artist/AddCommission.cshtml
@page
@model Presentation.Pages.Artist.AddCommissionModel
@{
}

@if(Model.IsRegisteredCommission)
{
	<h3>You already have one commission available.</h3>
}
else
{
	<div class="container">
		<form method="post">
			<div class="text-danger" asp-validation-summary="All"></div>
			<div class="mb-3">
				<label for="description" class="form-label">Description: </label>
				<input type="text" class="form-control" id="description" asp-for="AddCommisionDTO.Description">
				<span class="text-danger" asp-validation-for="AddCommisionDTO.Description"></span>
			</div>
			<div class="mb-3">
				<label for="targetPrice" class="form-label">Target price: </label>
				<input type="number" class="form-control" id="targetPrice" asp-for="AddCommisionDTO.TargetPrice">
				<span class="text-danger" asp-validation-for="AddCommisionDTO.TargetPrice"></span>
			</div>
			<div class="mb-3">
				<button type="submit" class="btn btn-success">Register your Commission</button>
			</div>
		</form>
	</div>
}

Presentation/Pages/Artist/ArtistCommission.cshtml
@page
@model ArtistCommissionModel
@{
}

@if (Model.Commission != null)
{
	<div class="container">
		<div class="row">
			<h3>Your commission overview:</h3>
		</div>
		<div class="row">
			<div class="card mb-3">
				<img src="" class="card-img-top" alt="">
				<div class="card-body">
					<h5 class="card-title">Specialization: </h5>
					<p class="card-text">@Model.Commission.Description</p>
					<p class="card-text">Target price: @Model.Commission.TargetPrice</p>
					<a href="#" class="btn btn-primary">Edit</a>
				</div>
			</div>
		</div>
	</div>
} 
else
{
	<h3>You do not have any commission to be displayed. Please add your commission if you want to.</h3>
	<p><a href="/artist/addcommission">Click here to add</a></p>
}

Presentation/Pages/Artist/ArtistCommissionHistory.cshtml
@page
@model Presentation.Pages.Artist.ArtistCommissionHistoryModel
@{
	var message = TempData["Message"] as string;
}

@if(!string.IsNullOrEmpty(message))
{
	<div class="alert alert-success">
		<p>@message</p>
	</div>
}

@if(Model.CommissionRequestHistoryDTOs != null && Model.CommissionRequestHistoryDTOs.Count != 0)
{
	<div class="container">
		<div class="row">
			<div style="height:20px;width:20px;background-color: rgba(236, 166, 13, 0.79); display:inline">
			</div>
			<div class="col-md-4">: Progress image request from audience</div>
		</div>
		<table class="table" id="commissionTable">
			<thead>
				<tr>
					<td>Sender Email</td>
					<td>Receiver Email</td>
					<td>Description</td>
					<td>Min Price</td>
					<td>Max Price</td>
					<td>Request Date</td>
					<td>Status</td>
					<td></td>
				</tr>
			</thead>
			<tbody>
				@foreach(var request in Model.CommissionRequestHistoryDTOs)
				{
					var style = "";
					@if(request.Status == 1)
					{
						style = "background-color: rgba(236, 166, 13, 0.79)";
					}

					<tr style="@Html.Raw(style)">
						<td>@request.SenderEmail</td>
						<td>@request.ReceiverEmail</td>
						<td>@request.RequestDescription</td>
						<td>@request.MinPrice</td>
						<td>@request.MaxPrice</td>
						<td>@request.RequestDate</td>
						<td>
							@if(request.CommissionStatusDescription == "Pending")
							{
								<p class="text text-warning">@request.CommissionStatusDescription</p>
							}
							else if(request.CommissionStatusDescription == "Accepted")
							{
								<p class="text text-success">@request.CommissionStatusDescription</p>
							}
							else if(request.CommissionStatusDescription == "Not Accepted")
							{
								<p class="text text-danger">@request.CommissionStatusDescription</p>
							}
							else if (request.CommissionStatusDescription == "In Progress")
							{
								<p class="text text-primary">@request.CommissionStatusDescription</p>
							}
							else
							{
								<p class="text text-info-emphasis">@request.CommissionStatusDescription</p>
							}
						</td>
						<td>
							@if (request.CommissionStatusDescription == "Pending")
							{
								<button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#acceptModal" id="openAcceptModal">Accept</button>
								<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmModal" id="openRejectModal">Reject</button>
								<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
									<div class="modal-dialog" role="document">
										<div class="modal-content">
											<div class="modal-header">
												<h5 class="modal-title" id="exampleModalLabel">Do you readly want to deny this commission?</h5>
												<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
													<span aria-hidden="true">&times;</span>
												</button>
											</div>
											<form method="post" asp-page-handler="NotAccept">
												<div class="modal-body">
													<div class="text text-danger" asp-validation-summary="All"></div>
													<input type="hidden" class="form-control" id="commissionId" asp-for="CommissionId" value="@request.Id" readonly>
													
													<div class="mb-3">
														<label for="reason" class="form-label">Reason: </label>
														<input type="text" class="form-control" id="reason" asp-for="NotAcceptedReason">
														<span class="text-danger" asp-validation-for="NotAcceptedReason"></span>
													</div>
												</div>
												<div class="modal-footer">
													<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
													<button type="submit" class="btn btn-primary">Submit</button>
												</div>
											</form>
										</div>
									</div>
								</div>
								<div class="modal fade" id="acceptModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
									<div class="modal-dialog" role="document">
										<div class="modal-content">
											<div class="modal-header">
												<h5 class="modal-title" id="exampleModalLabel">Do you readly want to accept this commission?</h5>
												<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
													<span aria-hidden="true">&times;</span>
												</button>
											</div>
											<form method="post" asp-page-handler="Accept">
												<div class="modal-body">
													<div class="text text-danger" asp-validation-summary="All"></div>
													<input type="hidden" class="form-control" id="commissionId" asp-for="CommissionId" value="@request.Id" readonly>
													<input type="hidden" class="form-control" id="commissionId" asp-for="MinPrice" value="@request.MinPrice" readonly>
													<input type="hidden" class="form-control" id="commissionId" asp-for="MaxPrice" value="@request.MaxPrice" readonly>
													<div class="mb-3">
														<label for="actualPrice" class="form-label">Actual Price: </label>
														<input type="number" class="form-control" id="actualPrice" asp-for="ActualPrice">
														<span class="text-danger" asp-validation-for="ActualPrice"></span>
													</div>
												</div>
												<div class="modal-footer">
													<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
													<button type="submit" class="btn btn-primary">Submit</button>
												</div>
											</form>
										</div>
									</div>
								</div>
							}
							else if(request.CommissionStatusDescription == "In Progress" || request.CommissionStatusDescription == "Accepted")
							{
								<a class="text" href="/artist/artistcommissionrequestdetail?id=@request.Id">View Detail</a>
							}
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
}
else
{
	<h3>No commission to be displayed</h3>
}
@section Scripts {
	<script>
		const accept = document.getElementById('openAcceptModal');
		const reject = document.getElementById('openRejectModal');
		let table = new DataTable('#commissionTable', {
			responsive: true
		});
	</script>
	@if(Model.IsInvalidAccept)
	{
		<script>
			accept.click();
		</script>
	}
	@if (Model.IsInvalidReject)
	{
		<script>
			reject.click();
		</script>
	}
	@if(Model.IsNotAcceptSuccess)
	{
		<script>
			var commissionConnection = new signalR.HubConnectionBuilder().withUrl("/commissionhub").build();
			commissionConnection.start().then(function () {
				commissionConnection.invoke("NotAcceptCommission", @Html.Raw(Json.Serialize(Model.CommissionId))).catch(function (err) {
					return console.error(err.toString());
				});
			}).catch(function (err) {
				return console.error(err.toString());
			});
		</script>
	}
	@if (Model.IsAcceptSuccess)
	{
		<script>
			var commissionConnection = new signalR.HubConnectionBuilder().withUrl("/commissionhub").build();
			commissionConnection.start().then(function () {
				commissionConnection.invoke("AcceptCommission", @Html.Raw(Json.Serialize(Model.CommissionId))).catch(function (err) {
					return console.error(err.toString());
				});
			}).catch(function (err) {
				return console.error(err.toString());
			});
		</script>
	}

	@if (Model.IsDoneSuccess)
	{
		<script>
			var commissionConnection = new signalR.HubConnectionBuilder().withUrl("/commissionhub").build();
			commissionConnection.start().then(function () {
				commissionConnection.invoke("DoneCommission", @Html.Raw(Json.Serialize(Model.CommissionId))).catch(function (err) {
					return console.error(err.toString());
				});
			}).catch(function (err) {
				return console.error(err.toString());
			});
		</script>
	}
}