Presentation/Pages/Account/ConfirmEmail.cshtml.cs
using BusinessObject.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using System.Text;

namespace Presentation.Pages.Account
{
    [AllowAnonymous]
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;

        public ConfirmEmailModel(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage { get; set; }
        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Account/LoginPage");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ConfirmEmailAsync(user, code);
            StatusMessage = result.Succeeded ? "Thank you for confirming your email." : "Error confirming your email.";
            return Page();
        }
    }
}

Presentation/Pages/Admin/Artwork/ArtworkList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;

namespace Presentation.Pages.Admin.Artwork;

[Authorize(Policy = "RequireAdminRole")]
public class ArtworkList : PageModel
{
    private readonly IArtworkRepository _artworkRepository;
    public ArtworkList(IArtworkRepository artworkRepository)
    {
        _artworkRepository = artworkRepository;
    }
    
    [BindProperty]
    public IList<BusinessObject.Entities.Artwork> Artworks { get; set; }
    public async Task OnGet()
    {
        Artworks = await _artworkRepository.GetArtworkAdmin();
    }

    public async Task<IActionResult> OnPostChangeStatus(int Id)
    {
        await _artworkRepository.ChangeArtworkStatusAdmin(Id);
        await OnGet();
        return Page();
    }
}

Presentation/Pages/Admin/User/UserAdd.cshtml.cs
using BusinessObject.DTOs;
using BusinessObject.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Presentation.Services;
using Repository;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;

namespace Presentation.Pages.Admin.User
{
    [Authorize(Policy = "RequireAdminRole")]

    public class UserAddModel : PageModel
    {
        private readonly IUserRepository _userRepository;
        private readonly RoleManager<AppRole> _roleManager;
        private readonly IValidator _validator;

        // Constructor
        public UserAddModel(
            IUserRepository userRepository, 
            RoleManager<AppRole> roleManager,
            IValidator validator)
        {
            _userRepository = userRepository;
            _roleManager = roleManager;
            _validator = validator;
        }

        // Properties
        [BindProperty]
        public AppUser AppUser { get; set; }

        [BindProperty]
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [EmailAddress]
        public string Email { get; set; }

        [BindProperty]
        [Required]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must be 10 digits")]
        public string PhoneNumber { get; set; }

        [BindProperty]
        [Required]
        [RegularExpression(@"^[a-zA-Z0-9 ]*$", ErrorMessage = "Username can only contain letters, digits, and spaces.")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)] public string Name { get; set; }

        [BindProperty]
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [BindProperty]
        public int SelectedRoleId { get; set; }
        [TempData]
        public string StatusMessage { get; set; }

        // OnGetAsync method
        public async Task<IActionResult> OnGetAsync()
        {
            // Populate roles in the dropdown list
            ViewData["Id"] = new SelectList(_roleManager.Roles.ToList(), "Id", "Name");
            return Page();
        }

        // OnPostAsync method
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                ViewData["Id"] = new SelectList(_roleManager.Roles.ToList(), "Id", "Name");
                return Page();
            }
            if (await _validator.ValidateEmail(Email))
            {
                ModelState.AddModelError(string.Empty, "Please enter exist email address");
                ViewData["Id"] = new SelectList(_roleManager.Roles.ToList(), "Id", "Name");
                return Page();
            }
            try
            {
                AppUser.Email = Email;
                AppUser.PhoneNumber = PhoneNumber;
                AppUser.Name = Name;
                Debug.WriteLine($"Email:{AppUser.Email}, Phone: {AppUser.PhoneNumber}, Name: {AppUser.Name}");

                var user = new AppUser
                {
                    EmailConfirmed = true,
                    Email = AppUser.Email,
                    PhoneNumber = AppUser.PhoneNumber,
                    Name = AppUser.Name,
                    UserName = AppUser.Name.ToLower(),
                    Status = 1,
                    UserImage = new UserImage
                    {
                        Url = "https://media.istockphoto.com/id/1341046662/vector/picture-profile-icon-human-or-people-sign-and-symbol-for-template-design.jpg?s=612x612&w=0&k=20&c=A7z3OK0fElK3tFntKObma-3a7PyO8_2xxW0jtmjzT78=",
                        isMain = true
                    }
                };

                await _userRepository.AddUser(user, Password);

                user.UserRoles = new List<AppUserRole>
                {
                    new AppUserRole
                    {
                        UserId = user.Id, 
                        RoleId = SelectedRoleId
                    }
                };
                await _userRepository.UpdateUser(user);
                return RedirectToPage("/Admin/User/UserManagement");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                ViewData["Id"] = new SelectList(_roleManager.Roles.ToList(), "Id", "Name");
                return Page();
            }

        }
    }
}

Presentation/Pages/Admin/User/UserDelete.cshtml.cs
using AutoMapper;
using BusinessObject.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;
using System.Diagnostics;

namespace Presentation.Pages.Admin.User
{
    [Authorize(Policy = "RequireAdminRole")]
    public class UserDeleteModel : PageModel
    {
        private readonly IUserRepository _userRepository;
        private readonly IMapper _mapper;
        public UserDeleteModel(IUserRepository userRepository, IMapper mapper)
        {
            _userRepository = userRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public AppUserDTO AppUserDTO { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            if (id == null || await _userRepository.GetUserDetailAdmin(id) == null)
            {
                return NotFound();
            }

            var user = await _userRepository.GetUserDetailAdmin(id);
            if (user == null)
            {
                return NotFound();
            }
            AppUserDTO = user;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var user = _mapper.Map<BusinessObject.Entities.AppUser>(AppUserDTO);
            Debug.WriteLine($"Email: {user.Email}");
            await _userRepository.DeleteUser(user);
            return RedirectToPage("./UserManagement");

        }
    }
}

Presentation/Pages/User/ChangeEmail.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Encodings.Web;
using BusinessObject.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace Presentation.Pages.User;

[Authorize]
public class ChangeEmail : PageModel
{
    private readonly UserManager<AppUser> _userManager;
    private readonly SignInManager<AppUser> _signInManager;
    private readonly IEmailSender _emailSender;

    public ChangeEmail(
        UserManager<AppUser> userManager,
        SignInManager<AppUser> signInManager,
        IEmailSender emailSender)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _emailSender = emailSender;
    }

    public string Email { get; set; }
    public bool IsEmailConfirmed { get; set; }
    [TempData]
    public string StatusMessage { get; set; }

    [BindProperty]
    public InputModel Input { get; set; }
    public class InputModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "New email")]
        public string NewEmail { get; set; }
    }

    private async Task LoadAsync(AppUser user)
    {
        var email = await _userManager.GetEmailAsync(user);
        Email = email;

        Input = new InputModel
        {
            NewEmail = email,
        };

        IsEmailConfirmed = await _userManager.IsEmailConfirmedAsync(user);
    }

    public async Task<IActionResult> OnGetAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        await LoadAsync(user);
        return Page();
    }

    public async Task<IActionResult> OnPostChangeEmailAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        if (!ModelState.IsValid)
        {
            await LoadAsync(user);
            return Page();
        }

        var email = await _userManager.GetEmailAsync(user);
        if (Input.NewEmail != email)
        {
            var userId = await _userManager.GetUserIdAsync(user);
            var code = await _userManager.GenerateChangeEmailTokenAsync(user, Input.NewEmail);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
                "/User/ConfirmEmailChange",
                pageHandler: null,
                values: new { area = "Identity", userId = userId, email = Input.NewEmail, code = code },
                protocol: Request.Scheme);
            await _emailSender.SendEmailAsync(
                Input.NewEmail,
                "Confirm your email",
                $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

            StatusMessage = "Confirmation link to change email sent. Please check your email.";
            return RedirectToPage();
        }

        StatusMessage = "Your email is unchanged.";
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostSendVerificationEmailAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        if (!ModelState.IsValid)
        {
            await LoadAsync(user);
            return Page();
        }

        var userId = await _userManager.GetUserIdAsync(user);
        var email = await _userManager.GetEmailAsync(user);
        var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
        code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
        var callbackUrl = Url.Page(
            "/User/ConfirmEmail",
            pageHandler: null,
            values: new { area = "Identity", userId = userId, code = code },
            protocol: Request.Scheme);
        await _emailSender.SendEmailAsync(
            email,
            "Confirm your email",
            $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

        StatusMessage = "Verification email sent. Please check your email.";
        return RedirectToPage();
    }
}

Presentation/Pages/User/Detail.cshtml.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using BusinessObject.DTOs;
using BusinessObject.Entities;
using DataAccess.Data;
using DataAccess.Management;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;

namespace Presentation.Pages.User;
[Authorize]
public class Detail : PageModel
{
    private readonly IUserRepository _userRepository;
    private UserManager<AppUser> _userManager;
    private SignInManager<AppUser> _signInManager;
    private DataContext _dataContext;
    public Detail(IUserRepository userRepository, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, DataContext dataContext)
    {
        _userRepository = userRepository;
        _userManager = userManager;
        _signInManager = signInManager;
        _dataContext = dataContext;
    }

    [BindProperty]
    public InputModel Input { get; set; }
    [BindProperty]
    public string image { get; set; }
    [BindProperty] 
    public AppUser AppUser { get; set; }
    [TempData]
    public string StatusMessage { get; set; }
    [BindProperty]
    public string Username { get; set; }
    public class InputModel
    {
        public string FullName { get; set; }
        public String ImageURL { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }
    
    public UserDetailDTO dto { get; set; }

    private async Task LoadAsync(AppUser appUser)
    {
        var userName = await _userRepository.GetUserDetailAdmin(appUser.Id);
        var userD = await _userRepository.getUserDetail(appUser);
        
        var userPhone = await _userManager.GetPhoneNumberAsync(appUser);
        Username = userName.Email;
        Input = new InputModel
        {
            FullName = userName.Name,
            ImageURL = userD.userImageUrl,
            Name = userName.Email,
            PhoneNumber = userPhone,
            Description = appUser.Description
        };
        
    }

    public async Task<IActionResult> OnGetAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Can not load user ID = '{_userManager.GetUserId(User)}'");
        }

        await LoadAsync(user);
        return Page();
    }

    public async Task<IActionResult> OnPostUpdate()
     {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Can not load user ID: ''{_userManager.GetUserId(User)}");
        }

        var phoneNumber = await _userManager.GetPhoneNumberAsync(user);
        if (Input.PhoneNumber != phoneNumber)
        {
            var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, Input.PhoneNumber);
            if (!setPhoneResult.Succeeded)
            {
                StatusMessage = "Error in updating Phone Number!";
                return RedirectToPage();
            }
        }
        // user.UserImage = Input.UserImage;
        user.Name = Input.FullName;
        // user.UserName = Username;
        user.Description = Input.Description;
        await _userManager.UpdateAsync(user);
            
        await _signInManager.RefreshSignInAsync(user);
        StatusMessage = "Your information have been updated!";
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostSign()
    {
        try
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                await _userRepository.SignAsArtist(user.Id);
                await _signInManager.RefreshSignInAsync(user);
                StatusMessage = "You has become an Artist! Be creative !";
                return RedirectToPage();
            }
            else
            {
                {
                    return NotFound($"Can not load user ID: ''{_userManager.GetUserId(User)}");
                }
            }
           
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
        
    }

    
   
}

Presentation/Pages/User/ArtworkList.cshtml
@page
@using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Manage.Internal
@model Presentation.Pages.User.ArtworkList

@{
    ViewData["Title"] = "Manage Artworks";
    ViewData["ActivePage"] = ManageNavPages.PersonalData;
}
<h4>@ViewData["Title"]</h4>
@* <partial name="_StatusMessage" model="Model.StatusMessage" /> *@
 @if (Model.Purchases == null || Model.Purchases.Count == 0)
    {
        <div class="alert alert-danger" role="alert">
            No artwork to display!
        </div>
    }
 else
 {
     <table id="artworkTable" class="table table-hover table-bordered dataTable" style="width:100%">
         <thead>
         <tr>
             <th scope="col">Artwork Id</th>
             <th scope="col">Artwork Title</th>
             <th scope="col">Author</th>
             <th scope="col">Price</th>
             <th scope="col">Buy Date</th>
             <th scope="col">Action</th>
         </tr>
         </thead>
         <tbody>
         @foreach (var item in Model.Purchases)
         {
             <tr>
                 <td>@item.Artwork.Id</td>
                 <td>@item.Artwork.Title</td>
                 <td>@item.Artwork.AppUser.Name</td>
                 <td>@item.BuyPrice.ToString("C", System.Globalization.CultureInfo.GetCultureInfoByIetfLanguageTag("en-US"))</td>
                 <td>@item.BuyDate</td>
                 <td>
                     <a asp-page="/Home/ArtworkDetail" asp-route-id="@item.Artwork.Id">
                         <button class="btn btn-sm btn-primary">
                             <i class="fas fa-eye"></i> Download Again
                         </button>
                     </a></td>


             </tr>
         }
         </tbody>
     </table>
     @section Scripts {
 <script>
         let table = new DataTable('#artworkTable', {
                    responsive: true
                });
    </script>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.13.1"></script>
     }

 }

Presentation/Pages/User/ChangeEmail.cshtml
@page
@using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Manage.Internal
@model Presentation.Pages.User.ChangeEmail

@{
    ViewData["Title"] = "Manage Email";
    ViewData["ActivePage"] = ManageNavPages.Email;
}
<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="Model.StatusMessage" />

<div class="row mt-3">
    <div class="col-md-3">
        <partial name="_ManageNav" />
    </div>
    <div class="col-md-6">
        <form id="email-form" method="post">
            <div asp-validation-summary="All" class="text-danger" role="alert"></div>

            <div class="form-floating mb-3 input-group">
                <input asp-for="Email" class="form-control" placeholder="Current Email" disabled />
                <div class="input-group-append">
                    <span class="input-group-text bg-success text-white font-weight-bold">✓</span>
                </div>
                <label asp-for="Email" class="form-label"></label>
            </div>

            <div class="form-floating mb-3">
                <input asp-for="Input.NewEmail" class="form-control" autocomplete="email" aria-required="true" placeholder="New Email">
                <label asp-for="Input.NewEmail" class="form-label"></label>
                <span asp-validation-for="Input.NewEmail" class="text-danger"></span>
            </div>

            <button id="change-email-button" type="submit" asp-page-handler="ChangeEmail" class="w-100 btn btn-lg btn-primary">Change Email</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Presentation/Pages/User/ChangePassword.cshtml
@page
@using Microsoft.AspNetCore.Identity.UI.V5.Pages.Account.Manage.Internal
@model Presentation.Pages.User.ChangePassword

@{
    ViewData["Title"] = "Manage Password";
    ViewData["ActivePage"] = ManageNavPages.ChangePassword;
}
<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="Model.StatusMessage" />

<div class="row mt-3">
    <div class="col-md-3">
        <partial name="_ManageNav" />
    </div>
    <div class="col-md-6">
        <form id="change-password-form" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
            
            <div class="form-floating mb-3">
                <input asp-for="Input.OldPassword" class="form-control" autocomplete="current-password" placeholder="Old Password" required />
                <label asp-for="Input.OldPassword" class="form-label"></label>
                <span asp-validation-for="Input.OldPassword" class="text-danger"></span>
            </div>
            
            <div class="form-floating mb-3">
                <input asp-for="Input.NewPassword" class="form-control" autocomplete="new-password" placeholder="New Password" required />
                <label asp-for="Input.NewPassword" class="form-label"></label>
                <span asp-validation-for="Input.NewPassword" class="text-danger"></span>
            </div>
            
            <div class="form-floating mb-3">
                <input asp-for="Input.ConfirmPassword" class="form-control" autocomplete="new-password" placeholder="Confirm New Password" required />
                <label asp-for="Input.ConfirmPassword" class="form-label"></label>
                <span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span>
            </div>
            
            <button type="submit" class="w-100 btn btn-lg btn-primary">Update Password</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Presentation/Pages/User/ConfirmEmail.cshtml
@page
@model Presentation.Pages.User.ConfirmEmail

@{
    ViewData["Title"] = "Confirm email";
}

<h1>@ViewData["Title"]</h1>
<partial name="_StatusMessage" model="Model.StatusMessage" />

Presentation/Pages/User/ConfirmEmailChange.cshtml
@page
@model Presentation.Pages.User.ConfirmEmailChange
@{
    ViewData["Title"] = "Confirm email change";
}

<h1>@ViewData["Title"]</h1>
<partial name="_StatusMessage" model="Model.StatusMessage" />

Presentation/Pages/User/Detail.cshtml
@page
@using BusinessObject.Entities
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.UI.V5.Pages.Account.Manage.Internal
@using Presentation.Extensions
@model Presentation.Pages.User.Detail
@inject SignInManager<AppUser> signInManager;
@{
    ViewData["Title"] = "User Profile";
    ViewData["ActivePage"] = ManageNavPages.Index;
}
<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="Model.StatusMessage" />

<div class="row">
    <div class="col-md-3">
        <partial name="_ManageNav" />
    </div>
    <div class="col-md-9">
        <form id="profile-form" method="post" asp-page-handler="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <img src="@Model.Input.ImageURL" style="width: 200px; height: 200px" alt="@Model.Input.ImageURL" class="img-fluid rounded-circle" />
            </div>

            <div class="form-group">
                <label asp-for="Input.FullName"></label>
                <input asp-for="Input.FullName" class="form-control" >
            </div>
            
            <div class="form-group">
                <label asp-for="Username"></label>
                <input asp-for="Username" class="form-control" disabled="">
            </div>

            <div class="form-group">
                <label asp-for="Input.Description"></label>
                <textarea asp-for="Input.Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Input.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Input.PhoneNumber"></label>
                <input type="number" asp-for="Input.PhoneNumber" class="form-control">
                <span asp-validation-for="Input.PhoneNumber" class="text-danger"></span>
            </div>

            <button id="update-profile-button" type="submit" class="btn btn-primary">Save Changes</button>
            
            <a asp-page="/Account/Logout" class="btn btn-danger">Log Out</a>
        </form>
    </div>
    @if (User.Identity.IsAuthenticated)
            {
                @if (User.IsInRole("Audience"))
                {
                    <form method="post" asp-page-handler="Sign">
                        <button type="submit" class="btn btn-primary">Become an Artist</button>
                    </form>
                }
               
            }
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}