Presentation/Pages/Home/ArtworkDetail.cshtml.cs
using BusinessObject.DTOs;
using BusinessObject.Entities;
using CloudinaryDotNet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Extensions;
using Presentation.Services;
using Repository;

namespace Presentation.Pages.Home
{
    [Authorize]
    public class ArtworkDetailModel : PageModel
    {
        private readonly IArtworkRepository _artworkRepository;
        private readonly IImageService _imageService;

        public ArtworkDetailModel(IArtworkRepository artworkRepository, IImageService imageService)
        {
            _artworkRepository = artworkRepository;
            _imageService = imageService;
        }

        public Artwork Artwork { get; set; } = default;
        [BindProperty]
        public AddCommentDTO AddComment { get; set; }
        [BindProperty]
        public AddLikeDTO AddLikeDTO { get; set; }
        [BindProperty]
        public AddFollowDTO AddFollowDTO { get; set; }
        [BindProperty]
        public AddPurchaseDTO addPurchaseDTO { get; set; }
        [BindProperty]
        public AddTransationDTO addTransationDTO{ get; set; }
        public IEnumerable<ArtworkComment> ArtworkComment { get; set; }
        public bool Likes { get; set; }
        public int UserId { get; set; }
        public bool Follows { get; set; }
        public bool Bought {  get; set; }
        public string DownloadUrl { get; set; }


        public async Task<IActionResult> OnGetAsync(int id)
        {
            if(id ==0)
            {
                return NotFound();
            }
            Artwork = await _artworkRepository.GetArtworkById(id);

            if(Artwork != null)
            {
                Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);
                ArtworkComment = await _artworkRepository.GetArtworkComments(id);
            
                Likes = await _artworkRepository.HasUserLikedArtwork(User.GetUserId(), id);
                Follows = await _artworkRepository.HasUserFollowed(User.GetUserId(), Artwork.AppUserId);
                Bought = await _artworkRepository.HasUserBought(User.GetUserId(), id);
                DownloadUrl = _imageService.GetImageUploadUrl(Artwork.ArtworkImage.PublicId);
            }
            UserId = User.GetUserId();
            return Page();
        }

        public async Task<IActionResult> OnPostComment()
        {
            //Keep Page State
            Artwork = await _artworkRepository.GetArtworkById(AddComment.Artworkid);
            Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);

            if (Artwork != null)
            {
                Likes = await _artworkRepository.HasUserLikedArtwork(User.GetUserId(), AddComment.Artworkid);
                Follows = await _artworkRepository.HasUserFollowed(User.GetUserId(), Artwork.AppUserId);
                Bought = await _artworkRepository.HasUserBought(User.GetUserId(), AddComment.Artworkid);
                DownloadUrl = _imageService.GetImageUploadUrl(Artwork.ArtworkImage.PublicId);
            }
            UserId = User.GetUserId();
            //
            AddComment.AppUserId = User.GetUserId();
            AddComment.CreatedDate = DateTime.Now;
            AddComment.Content = Request.Form["comment"];

            if (!ModelState.IsValid) return Page();
            try
            {
                await _artworkRepository.AddArtworkComment(AddComment.Artworkid, AddComment.AppUserId, AddComment.Content, AddComment.CreatedDate);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            ArtworkComment = await _artworkRepository.GetArtworkComments(AddComment.Artworkid);
            return Page();
        }

        public async Task<IActionResult> OnPostLike()
        {
            //Keep Page State
            Artwork = await _artworkRepository.GetArtworkById(AddLikeDTO.ArtworkId);
            Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);
            ArtworkComment = await _artworkRepository.GetArtworkComments(AddLikeDTO.ArtworkId);
            
            UserId = User.GetUserId();
            //
            AddLikeDTO.AppUserId = User.GetUserId();
            if (!ModelState.IsValid) return Page();
            try
            {
                await _artworkRepository.LikeArtwork(AddLikeDTO.AppUserId, AddLikeDTO.ArtworkId);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            if (Artwork != null)
            {
                Likes = await _artworkRepository.HasUserLikedArtwork(User.GetUserId(), AddLikeDTO.ArtworkId);
                Follows = await _artworkRepository.HasUserFollowed(User.GetUserId(), Artwork.AppUserId);
                Bought = await _artworkRepository.HasUserBought(User.GetUserId(), AddLikeDTO.ArtworkId);
                DownloadUrl = _imageService.GetImageUploadUrl(Artwork.ArtworkImage.PublicId);
            }
            return Page();
        }

        public async Task<IActionResult> OnPostFollow()
        {
            //Keep Page State
            Artwork = await _artworkRepository.GetArtworkById(AddLikeDTO.ArtworkId);
            Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);
            ArtworkComment = await _artworkRepository.GetArtworkComments(AddLikeDTO.ArtworkId);
            
            UserId = User.GetUserId();
            //
            if (AddFollowDTO != null)
            {
                AddFollowDTO.AppUserId = User.GetUserId();
            } 
            if (!ModelState.IsValid) return Page();
            try
            {
                await _artworkRepository.FollowArtist(AddFollowDTO.TargetUserId, AddFollowDTO.AppUserId);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            if (Artwork != null)
            {
                Likes = await _artworkRepository.HasUserLikedArtwork(User.GetUserId(), AddLikeDTO.ArtworkId);
                Follows = await _artworkRepository.HasUserFollowed(User.GetUserId(), Artwork.AppUserId);
                Bought = await _artworkRepository.HasUserBought(User.GetUserId(), AddLikeDTO.ArtworkId);
                DownloadUrl = _imageService.GetImageUploadUrl(Artwork.ArtworkImage.PublicId);
            }
            return Page();
        }
        
        public async Task<IActionResult> OnPostBuy()
        {
            //Keep Page State
            Artwork = await _artworkRepository.GetArtworkById(AddLikeDTO.ArtworkId);
            Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);
            ArtworkComment = await _artworkRepository.GetArtworkComments(AddLikeDTO.ArtworkId);
            if (Artwork != null)
            {
                Likes = await _artworkRepository.HasUserLikedArtwork(User.GetUserId(), AddLikeDTO.ArtworkId);
                Follows = await _artworkRepository.HasUserFollowed(User.GetUserId(), Artwork.AppUserId);
                DownloadUrl = _imageService.GetImageUploadUrl(Artwork.ArtworkImage.PublicId);
            }
            UserId = User.GetUserId();
            //
            addPurchaseDTO.ArtworkId = AddLikeDTO.ArtworkId;
            addTransationDTO.SenderId = User.GetUserId();
            addTransationDTO.ReceiverId = Artwork.AppUserId;
            addTransationDTO.Money = addPurchaseDTO.BuyPrice;
            if (addPurchaseDTO != null)
            {
                addPurchaseDTO.AppUserId = User.GetUserId();
            } 
            if (!ModelState.IsValid) return Page();
            try
            {
                await _artworkRepository.BuyArtwork(addPurchaseDTO,addTransationDTO);
                TempData["Message"] = "Artwork has been Bought successfully!";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            Bought = await _artworkRepository.HasUserBought(User.GetUserId(), AddLikeDTO.ArtworkId);
            return Page();
        }

        /*public async Task<IActionResult> OnPostDownload()
        {
            //Keep Page State
            Artwork = await _artworkRepository.GetArtworkById(AddLikeDTO.ArtworkId);
            Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);
            ArtworkComment = await _artworkRepository.GetArtworkComments(AddLikeDTO.ArtworkId);
            if (Artwork != null)
            {
                Likes = await _artworkRepository.HasUserLikedArtwork(User.GetUserId(), AddLikeDTO.ArtworkId);
                Follows = await _artworkRepository.HasUserFollowed(User.GetUserId(), Artwork.AppUserId);
                Bought = await _artworkRepository.HasUserBought(User.GetUserId(), AddLikeDTO.ArtworkId);
            }
            UserId = User.GetUserId();
            //
            
            if (!ModelState.IsValid) return Page();
            try
            {
                
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            
            return Page();
        }*/
    }
}

Presentation/Pages/Home/Index.cshtml.cs
using BusinessObject.DTOs;
using BusinessObject.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Presentation.Extensions;
using Presentation.Services;
using Repository;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Presentation.Pages.Home
{


    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IArtworkRepository _artworkRepository;
        private readonly IImageService _imageService;

        public IndexModel(IArtworkRepository artworkRepository, IImageService imageService)
        {
            _artworkRepository = artworkRepository;
            _imageService = imageService;
        }

        public IEnumerable<Artwork> Artworks { get; set; } 
        [BindProperty]
        public AddLikeDTO AddLikeDTO { get; set; }
        [BindProperty]
        public AddFollowDTO AddFollowDTO { get; set; }

        //Paging--------------------------------------------------------------------
        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 1;
        public int Count { get; set; }
        public int PageSize { get; set; } = 10;

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));
        //----------------------------------------------------------------------------
        public async Task OnGetAsync()
        {
            Artworks = await _artworkRepository.GetPaginatedResult(CurrentPage, PageSize);
            foreach (var Artwork in Artworks)
            {
                Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);
            }
            Count = await _artworkRepository.GetCount();
            /*Artworks = await _artworkRepository.GetArtworks();*/

        }

        public async Task<IActionResult> OnPostIndex(string title)
        {
            if (System.String.IsNullOrEmpty(title))
            {
                Artworks = await _artworkRepository.GetArtworks();
                foreach (var Artwork in Artworks)
                {
                    Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);
                }
                return Page();

            }
            else
            {
                Artworks = await _artworkRepository.GetArtworkByTitle(title);
                foreach (var Artwork in Artworks)
                {
                    Artwork.ArtworkImage.Url = _imageService.GetImageUploadUrl2(Artwork.ArtworkImage.PublicId);
                }
                return Page();
            }
        }
    }
}

Presentation/Pages/Home/ArtworkDetail.cshtml
@page
@model Presentation.Pages.Home.ArtworkDetailModel
@{
}
@if (Model.Artwork != null)
{
    
    <h1>@Model.Artwork.Title</h1>

    <div>
        <img src="@Model.Artwork.ArtworkImage.Url" alt="@Model.Artwork.Title" class="img-fluid" />
        <p><strong>Description:</strong> @Model.Artwork.Description</p>
        <p><strong>Genre:</strong> @Model.Artwork.Genre.Name</p>
        <p><strong>Price:</strong> @Model.Artwork.Price</p>
        <p><strong>Artist:</strong> <a asp-page="/Audience/ArtistPage" asp-route-userId=@Model.Artwork.AppUserId > @Model.Artwork.AppUser.Name </a> </p>
    </div>
    <form method="post"> 
                            <div class="text text-danger" asp-validation-summary="All"></div> 
        <input type="hidden" asp-for="AddLikeDTO.ArtworkId" value="@Model.Artwork.Id" />
        <input type="hidden" asp-for="addPurchaseDTO.BuyPrice" value="@Model.Artwork.Price" />
        <input type="hidden" asp-for="AddFollowDTO.TargetUserId" value="@Model.Artwork.AppUserId" />
        @if (Model != null && Model.Artwork != null && Model.Likes != null)
        {
            <button type="submit" class="btn btn-primary like-state" data-artwork-id="@Model.Artwork.Id"
                    data-like-state="@Model.Likes" asp-page-handler="Like" asp-page="./ArtworkDetail" asp-route-id="@Model.Artwork.Id" >
                @if (Model.Likes)
                {
                    <text> Liked </text>
                }
                else
                {
                    <text> Like </text>
                }
            </button>
        }
        
        
        @if (Model.Artwork.AppUserId != Model.UserId)
        {
            <button type="submit" class="btn btn-secondary" asp-page-handler="Follow">
                @if (Model.Follows)
                {
                    <text> Followed </text>
                }
                else
                {
                    <text> Follow </text>
                }
            </button>
            @if (!Model.Bought)
            {
                <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#confirmPurchaseModal">Buy Artwork</button>
            } else
            {
                <button type="button" class="btn btn-secondary" onclick="downloadFile()" @* asp-page-handler="Download" *@>Download Bought-Artwork</button>
            }
        }
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-success" role="alert">
                @TempData["Message"]
            </div>
        }
        <div class="modal fade" id="confirmPurchaseModal" tabindex="-1" aria-labelledby="confirmPurchaseModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmPurchaseModalLabel">Buy Artwork Confirmation</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Do you really want to buy this image ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-primary" id="confirmPurchaseButton" asp-page-handler="Buy">Yes</button>
                    </div>
                </div>
            </div>
        </div>

    </form>
    <br />
    <br />
    <div id="comment-section">
        <!-- Comments will be displayed here -->
        @foreach (var artwork in Model.ArtworkComment)
        {
            <div>
                <p><strong>User Name:</strong> @artwork.AppUser.Name</p>
                <p><strong>Content:</strong> @artwork.Content</p>
                <p><strong>Comment Date:</strong> @artwork.CreatedDate</p>
            </div>
        }
        <br />
    </div>
}
<hr />
@if (Model.Artwork != null)
{
    <!-- Form for submitting new comments -->
    <form id="comment-form" method="post" asp-page-handler="Comment" asp-route-artworkId="@Model.Artwork.Id">
        <div class="form-group">
            <label for="comment">Add a Comment:</label>
            <textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
        </div>
        <div class="text text-danger" asp-validation-summary="All"></div>
        <input type="hidden" asp-for="AddComment.Artworkid" value="@Model.Artwork.Id" />
        <button type="submit" class="btn btn-primary">Comment</button>
    </form>
}
else
{
    <div>
        <p>Artwork not found.</p>
    </div>
}
@section Scripts {
    <script>
        
        document.getElementById('confirmPurchaseButton').addEventListener('click', function () {

            $('#confirmPurchaseModal').modal('hide');
        });

        function downloadFile() {
            
            var url = '@Model.DownloadUrl';

            var anchor = document.createElement('a');
            anchor.href = url;
            anchor.download = 'ArtworkSharing'; 
            document.body.appendChild(anchor); 
            anchor.click(); 
            document.body.removeChild(anchor); 
        }
    </script>
}

Presentation/Pages/Home/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@* <style> *@
@*     /* Custom CSS styles */ *@
@*     .user-detail { *@
@*         margin-bottom: 50px; /* Tăng khoảng cách giữa Phần Detail User và Phần Gallery */ *@
@*     } *@
@* *@
@*     .artwork-image { *@
@*         width: 100%; /* Set the width to 100% */ *@
@*         height: auto; /* Automatically calculate the height to maintain aspect ratio */ *@
@*         max-width: 1000px; /* Set a maximum width for the images */ *@
@*     } *@
@* </style> *@

<h1>Artworks</h1>
<form method="post" asp-page="/Home/Index" asp-page-handler="Index"  id="searchForm">
    <div class="search">
        <span id="search-icon" class="material-symbols-outlined">search</span>
        <input name="title" id="search-title" class="search-input" type="search" placeholder="Search anything"/>
    </div>
</form>
<style>
    .search{
      --padding: 14px;
      
      width: max-content;
      display: flex;
      align-items: center;
      padding: var(--padding);
      border-radius: 28px;
      background: #f6f6f6;
      transition: box-shadow 0.25s;
    }
    
    .search:focus-within{
      box-shadow: 0 0 2px rgba(0, 0, 0 , 0.75);
      
    }
    
    .search-input{
      font-size: 14px ;
      font-family: 'Lexend', sans-serif;
      color: #333333;
      margin-left: var(--padding);
      outline: none;
      border: none;
      background: transparent;
      width: 800px;  
    }
    
    .search-input::placeholder{
      color: rgba(0, 0, 0, 0.5);
    }

    .project-text-inner img {
        width: 200px; 
        height: 200px; 
        object-fit: fill; 
        display: block;
        margin: 0 auto; 
    }

</style>
<br/>
<div class="hero-full-wrapper">
    <div class="grid" style="position: relative; height: 1870.52px;">
        <div class="gutter-sizer"></div>
        <div class="grid-sizer"></div>
    @if (Model.Artworks != null)
    {
        @foreach (var artwork in Model.Artworks)
        {
            <br />
                        
            <div class="grid-item" style="position: absolute; left: 0px; top: 0px;">
                    <img style="border-radius: 10px" class="img-responsive" alt="@artwork.Title" src="@artwork.ArtworkImage.Url">
                <a asp-page="./ArtworkDetail" asp-route-id="@artwork.Id"class="project-description">
                    <div class="project-text-holder">
                        <div class="project-text-inner">
                            <h3></h3>
                            <p asp-page="./ArtworkDetail" asp-route-id="@artwork.Id">Discover more</p>
                        </div>
                    </div>
                </a>
            </div>

            
            <br />
        }
            @* <div class="grid-item" style="position: absolute; left: 0px; top: 0px;">
                <img style="border-radius: 10px" class="img-responsive" alt="@artwork.Title" src="@artwork.ArtworkImage.Url">
                <a asp-page="./ArtworkDetail" asp-route-id="11" class="project-description">
                    <div class="project-text-holder">
                        <div class="project-text-inner">
                            <h3>@artwork.Title</h3>
                            <p asp-page="./ArtworkDetail" asp-route-id="@artwork.Id">Discover more</p>
                        </div>
                    </div>
                </a>
            </div> *@
    }
    </div>
</div>

<div>
    <ul class="pagination">
        @for (var i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                <a asp-page="/Home/Index" asp-route-currentpage="@i" class="page-link">@i</a>
            </li>
        }
    </ul>
</div>
    
@section Scripts
    {
        <script>
            $(function() {
                $("#search-icon").click(function() {
                    $("#searchForm").submit(); // Submit the form
                });
            });
        </script>
    }